#!/usr/bin/env node
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const AdmZip=require('../../../backend/node_modules/adm-zip');
const root=__dirname, api=(process.env.FUXI_API_URL||'http://192.168.2.145:16077').replace(/\/$/,'');
if(process.argv[2]!=='SEED_FUXI_TEST'||!api.includes(':16077'))throw new Error('仅允许使用 SEED_FUXI_TEST 写入 16077');
function loadConfig(){const file=path.join(process.env.USERPROFILE||'','.codex','skills','fuxi-platform-release','config.env');if(!fs.existsSync(file))return;for(const line of fs.readFileSync(file,'utf8').split(/\r?\n/)){const m=line.match(/^([A-Z0-9_]+)=(.*)$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^['"]|['"]$/g,'')}}
loadConfig();if(!process.env.FUXI_USERNAME||!process.env.FUXI_PASSWORD)throw new Error('缺少 FUXI_USERNAME/FUXI_PASSWORD');
let token='';async function req(url,{method='GET',body,form}={}){const headers={};if(token)headers.Authorization=`Bearer ${token}`;if(body){headers['Content-Type']='application/json';body=JSON.stringify(body)}const res=await fetch(`${api}${url}`,{method,headers,body:form||body});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(`${method} ${url}: ${data.message||res.status}`);return data.data}
const specs=[
 {slug:'entity-modeling',name:'天宫业务域实体建模',desc:'业务域树、实体清单、字段配置与血缘关系维护',image:'entity-modeling.png',path:'modeling/domain/entity'},
 {slug:'method-modeling',name:'天宫业务方法建模',desc:'业务方法、英文名称、技术类别与服务编排维护',image:'method-modeling.png',path:'modeling/domain/method'},
 {slug:'frontend-api',name:'天宫前端接口建模',desc:'前端接口、业务场景、业务模型与服务编排维护',image:'frontend-api.png',path:'modeling/domain/frontend-api'},
 {slug:'capability-api',name:'天宫能力接口建模',desc:'能力接口、调用路径、业务模型与血缘关系维护',image:'capability-api.png',path:'modeling/domain/capability-api'}
];
function zipFor(spec){const zip=new AdmZip();const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${spec.name}</title><style>*{box-sizing:border-box}body{margin:0;background:#eef2f8;font:14px Microsoft YaHei;color:#1c2740}.bar{height:54px;display:flex;align-items:center;gap:16px;padding:0 24px;background:#fff;border-bottom:1px solid #dfe5ef}.bar b{font-size:17px}.tag{padding:3px 8px;border-radius:12px;color:#2f65e9;background:#edf3ff}.screen{margin:18px auto;width:min(1540px,calc(100vw - 36px));overflow:hidden;border:1px solid #dae1ec;border-radius:10px;background:#fff;box-shadow:0 10px 30px #263d6518}.screen img{display:block;width:100%;height:auto}.hint{padding:9px 18px;color:#65728a;background:#fff}</style></head><body><div class="bar"><b>${spec.name}</b><span class="tag">真实天宫界面参考</span><span>${spec.desc}</span></div><div class="screen"><img src="screen.png" alt="${spec.name}"><div class="hint">演示数据仅用于伏羲项目协作与快速手册截图，不连接真实业务数据。</div></div></body></html>`;zip.addFile('index.html',Buffer.from(html));zip.addLocalFile(path.join(root,'assets',spec.image),'','screen.png');return zip.toBuffer()}
async function formUpload(url,buffer,note){const form=new FormData();form.append('file',new Blob([buffer],{type:'application/zip'}),'prototype.zip');form.append('versionNote',note);form.append('versionType','minor');return req(url,{method:'POST',form})}
async function ensureUser(username,nickname){let users=await req(`/api/auth/users/search?keyword=${encodeURIComponent(username)}`);let user=users.find(x=>x.username===username);if(!user)user=await req('/api/auth/users',{method:'POST',body:{username,password:crypto.randomBytes(18).toString('base64url'),nickname,role:['uploader']}});return user}
async function main(){
 const login=await req('/api/auth/login',{method:'POST',body:{username:process.env.FUXI_USERNAME,password:process.env.FUXI_PASSWORD}});token=login.token;
 const members=[await ensureUser('modelingentity','陈雨（演示）'),await ensureUser('modelingapi','赵明（演示）')];
 const list=await req('/api/prototypes?scope=all&page=1&pageSize=100&keyword='+encodeURIComponent('天宫'));
 for(const spec of specs){let p=list.find(x=>x.name===spec.name);if(!p)p=await req('/api/prototypes',{method:'POST',body:{name:spec.name,description:spec.desc,tags:['天宫','建模开发','演示数据']}});spec.prototype=p;const zip=zipFor(spec);await formUpload(`/api/prototypes/${p.id}/upload`,zip,'建模开发平台演示基线');spec.zip=zip}
 const projects=await req('/api/projects?scope=all&page=1&pageSize=100&keyword='+encodeURIComponent('建模开发平台'));let project=projects.find(x=>x.name==='建模开发平台');
 const menuConfig={items:[{key:'modeling',label:'建模设计',children:[{key:'domain',label:'业务域建模',children:[{key:'entity',label:'实体建模',children:[]},{key:'method',label:'方法建模',children:[]},{key:'frontend-api',label:'前端接口',children:[]},{key:'capability-api',label:'能力接口',children:[]}]}]},{key:'integration',label:'连接集成',children:[{key:'prompt',label:'提示语管理',children:[]},{key:'mapping',label:'映射管理',children:[]}]},{key:'permission',label:'权限与组织',children:[{key:'users',label:'用户管理',children:[]},{key:'roles',label:'角色管理',children:[]},{key:'groups',label:'用户组管理',children:[]}]},{key:'workflow',label:'流程与服务',children:[{key:'approval',label:'审批流程设计',children:[]},{key:'orchestration',label:'服务编排',children:[]},{key:'scheduling',label:'任务调度',children:[]}]}]};
 if(!project)project=await req('/api/projects',{method:'POST',body:{name:'建模开发平台',description:'基于真实天宫建模场景的项目协作演示，用于快速手册截图。',menuConfig}});else project=await req(`/api/projects/${project.id}`,{method:'PUT',body:{name:project.name,description:'基于真实天宫建模场景的项目协作演示，用于快速手册截图。',menuConfig}});
 let detail=await req(`/api/projects/${project.id}`);for(const spec of specs){if(!detail.prototypes.some(x=>x.prototype_id===spec.prototype.id&&x.menu_path===spec.path))await req(`/api/projects/${project.id}/prototypes`,{method:'POST',body:{prototypeId:spec.prototype.id,menuPath:spec.path}})}
 for(const member of members)await req(`/api/projects/${project.id}/members`,{method:'POST',body:{userId:member.id,role:'editor'}});
 detail=await req(`/api/projects/${project.id}`);const taskSpecs=[['实体字段批量导入增加校验','entity-modeling','增加重复字段、类型冲突和必填项校验提示'],['方法列表补充技术类别筛选','method-modeling','增加技术类别和业务场景组合筛选'],['前端接口列表优化列宽','frontend-api','优化长英文名称和服务路径的展示'],['能力接口增加调用关系提示','capability-api','在能力接口列表补充调用关系入口']];
 for(const [title,slug,requirement] of taskSpecs){const spec=specs.find(x=>x.slug===slug),changes=await req(`/api/projects/${project.id}/changes?prototypeId=${spec.prototype.id}`);if(changes.some(x=>x.title===title))continue;const created=await req(`/api/projects/${project.id}/prototypes/${spec.prototype.id}/changes`,{method:'POST',body:{title,requirement,versionStrategy:{type:'auto'}}});if(slug==='frontend-api'){await req('/api/projects/handoffs/redeem',{method:'POST',body:{handoffCode:created.handoffCode}});const form=new FormData();form.append('file',new Blob([spec.zip],{type:'application/zip'}),'candidate.zip');form.append('versionType','minor');await req(`/api/projects/${project.id}/changes/${created.change.id}/candidate`,{method:'POST',form})}}
 const snapshots=await req(`/api/projects/${project.id}/snapshots`);if(!snapshots.some(x=>x.name==='建模模块分工基线'))await req(`/api/projects/${project.id}/snapshots`,{method:'POST',body:{name:'建模模块分工基线',versionLabel:'v1.0'}});
 detail=await req(`/api/projects/${project.id}`);const ability=detail.prototypes.find(x=>x.menu_path==='modeling/domain/capability-api');if(ability&&!ability.checkout)await req(`/api/projects/${project.id}/prototypes/${ability.id}/checkout`,{method:'POST',body:{note:'能力接口联调演示',durationHours:24}});
 console.log(JSON.stringify({projectId:project.id,projectName:project.name,prototypes:specs.map(x=>({id:x.prototype.id,name:x.name,path:x.path})),members:members.map(x=>x.nickname),testUrl:`${api}/projects/${project.id}`},null,2));
}
main().catch(error=>{console.error(error.message);process.exitCode=1});
